/* Wealth Arrays calculator search — single resilient owner for calculator and library search. */
(function () {
  'use strict';
  if (window.__WA_CALCULATOR_SEARCH_LOADED__) return;
  window.__WA_CALCULATOR_SEARCH_LOADED__ = true;
  const CATALOG=[['SIP Calculator','/sip-calculator/','Monthly investing and projected wealth.','sip systematic investment plan monthly mutual fund investing'],['Compound Interest','/compound-interest-calculator/','See how compounding changes growth over time.','compound interest compounding savings growth investing'],['Mortgage / EMI','/mortgage-emi-calculator/','Estimate monthly payment and total interest.','mortgage emi home loan loan payment interest'],['ROI Calculator','/roi-calculator/','Measure total and annualized investment return.','roi return investment profit annualized'],['Simple Interest','/simple-interest-calculator/','Calculate flat interest on principal.','simple interest banking loan deposit'],['Retirement Calculator','/retirement-calculator/','Estimate a financial-independence target.','retirement fire pension financial independence goal'],['Salary to Hourly','/salary-to-hourly-calculator/','Convert annual salary and hourly pay.','salary hourly wage income pay'],['Profit Margin','/profit-margin-calculator/','Calculate revenue, cost and margin.','profit margin business revenue cost'],['Fixed Deposit','/fixed-deposit-calculator/','Project deposit growth and maturity value.','fixed deposit fd banking maturity interest'],['Recurring Deposit','/recurring-deposit-calculator/','Plan monthly deposits and maturity value.','recurring deposit rd monthly banking maturity'],['Lumpsum Calculator','/lumpsum-calculator/','Project a one-time investment.','lumpsum lump sum investment one time'],['CAGR Calculator','/cagr-calculator/','Calculate compound annual growth rate.','cagr compound annual growth rate return'],['Car Loan EMI','/car-loan-calculator/','Plan vehicle-loan payments and interest.','car loan auto vehicle emi repayment'],['Personal Loan','/personal-loan-calculator/','Estimate personal-loan repayment cost.','personal loan emi payment repayment'],['Debt Payoff','/debt-payoff-calculator/','Plan a faster route out of debt.','debt payoff repayment credit loan'],['Inflation Calculator','/inflation-calculator/','Understand future purchasing power.','inflation future value purchasing power prices'],['Net Worth','/net-worth-calculator/','Track assets minus liabilities.','net worth assets liabilities wealth'],['Overtime Pay','/overtime-pay-calculator/','Estimate overtime earnings.','overtime pay salary wage income'],['Freelance Rate','/freelance-rate-calculator/','Turn target income into an hourly rate.','freelance rate hourly pricing business income'],['Income Tax Scenario Calculator','/income-tax-scenario-calculator/','Explore tax scenarios using an effective-rate assumption.','income tax tax scenario effective rate planning']];
  const ALIASES={sip:'systematic investment plan monthly mutual fund',emi:'mortgage home loan monthly payment',fd:'fixed deposit banking',rd:'recurring deposit monthly banking',roi:'return investment profit',cagr:'compound annual growth return',tax:'income tax scenario',salary:'hourly wage income',loan:'mortgage personal car debt',retirement:'pension financial independence',inflation:'purchasing power future prices',lumpsum:'lump sum investment one time',networth:'assets liabilities wealth','net worth':'assets liabilities wealth','compound interest':'compounding growth','simple interest':'flat interest','profit margin':'business revenue cost margin','car loan':'vehicle loan emi','personal loan':'loan repayment',freelance:'freelance rate hourly pricing',overtime:'overtime pay salary'};
  const normalize=v=>String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
  const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function score(c,q){const t=normalize(c[0]),s=normalize(c[1]),k=normalize(c[3]),d=normalize(c[2]),a=normalize(ALIASES[q]||'');let n=0;if(t===q)n+=500;if(t.includes(q))n+=250;if(s.includes(q))n+=180;if(k.includes(q))n+=160;if(d.includes(q))n+=60;for(const x of normalize(`${q} ${a}`).split(' ').filter(Boolean))if(x.length>1&&(t.includes(x)||k.includes(x)||s.includes(x)))n+=x===q?35:8;return n;}
  function nodes(){return{input:document.getElementById('tool-search'),box:document.getElementById('tool-search-results')}}
  function install(){
    const calc=!!document.querySelector('.calc-page'),lib=!!document.querySelector('.tool-library-search');if(!calc&&!lib)return false;
    let{input,box}=nodes();if(!input||!box)return false;
    if(input.dataset.waSearchOwner==='calculator-search')return true;
    input.dataset.waSearchOwner='calculator-search';
    const shell=input.closest('.tool-search-shell,.search-bar,.tool-library-search,.calc-page');
    if(shell){shell.style.position='relative';shell.style.zIndex='1000';shell.style.overflow='visible'}
    Object.assign(box.style,{position:'absolute',top:'calc(100% + 8px)',left:'0',right:'0',width:'100%',zIndex:'99999',maxHeight:'350px',overflowY:'auto',overflowX:'hidden',background:'var(--surface,#fff)',border:'1px solid var(--line,#e2e6ed)',borderRadius:'14px',boxShadow:'0 10px 25px rgba(0,0,0,.15)'});
    const hide=()=>{box.hidden=true;box.style.display='none'},show=()=>{box.hidden=false;box.style.setProperty('display','block','important')};
    const render=()=>{const q=normalize(input.value);if(!q){box.innerHTML='';hide();if(lib)document.querySelectorAll('.tools-grid .tool-card').forEach(c=>c.hidden=false);return}
      if(lib){const terms=normalize(`${q} ${ALIASES[q]||''}`).split(' ').filter(Boolean),cards=[...document.querySelectorAll('.tools-grid .tool-card')],matches=cards.map(card=>{const h=normalize(`${card.querySelector('h2')?.textContent||''} ${card.dataset.search||''} ${card.querySelector('p')?.textContent||''}`);let n=h.includes(q)?300:0;for(const x of terms)if(x.length>1&&h.includes(x))n+=x===q?30:5;return{card,score:n}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);cards.forEach(c=>c.hidden=!matches.some(x=>x.card===c));box.innerHTML=matches.slice(0,8).map(({card})=>{const t=card.querySelector('h2')?.textContent?.trim()||'Calculator',d=card.querySelector('p')?.textContent?.trim()||'';return`<a class="wa-search-suggestion" href="${esc(card.getAttribute('href')||'#')}"><span><strong>${esc(t)}</strong><small>${esc(d)}</small></span><b aria-hidden="true">→</b></a>`}).join('')||'<div class="tool-search-empty">No calculator found. Try SIP, EMI, FD, RD, loan, tax or ROI.</div>'}
      else{const results=CATALOG.map(c=>({c,score:score(c,q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,8);box.innerHTML=results.length?results.map(({c})=>`<a class="wa-search-suggestion" href="${esc(c[1])}"><span><strong>${esc(c[0])}</strong><small>${esc(c[2])}</small></span><b aria-hidden="true">→</b></a>`).join(''):'<div class="tool-search-empty">No calculator found. Try SIP, EMI, FD, RD, loan, tax, salary or ROI.</div>'}show()};
    input.addEventListener('input',render);input.addEventListener('search',render);input.addEventListener('keyup',render);input.addEventListener('focus',render);input.addEventListener('keydown',e=>{if(e.key==='Escape'){hide();input.blur()}});document.addEventListener('click',e=>{if(!input.contains(e.target)&&!box.contains(e.target))hide()});window.WA_CALCULATOR_SEARCH_CATALOG=CATALOG;window.__WA_SEARCH_READY__=true;render();return true;
  }
  function boot(){if(install())return;const observer=new MutationObserver(()=>{if(install())observer.disconnect()});observer.observe(document.documentElement,{childList:true,subtree:true});[50,150,300,600,1200,2500].forEach(ms=>setTimeout(install,ms))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
