/* Wealth Arrays final polish: clean footer branding, category accents, PDF branding, scale-safe result visuals. */
(function(){
'use strict';
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function cleanNum(v){let s=String(v||'').replace(/[^0-9.eE+-]/g,'');let n=Number(s);return Number.isFinite(n)?n:NaN;}
function tidyHeader(){document.querySelectorAll('#language-select').forEach(s=>{if(!s.options.length||!s.value||!Array.from(s.options).some(o=>o.value)){s.remove();}});}
function footerLogo(){
 document.querySelectorAll('.footer-mark').forEach(a=>{
  a.innerHTML='<img src="/favicon-v2.svg" alt="Wealth Arrays" class="wa-footer-logo"><span>Wealth Arrays</span><sup>®</sup>';
  a.dataset.waLogoFixed='1';
 });
 document.querySelectorAll('.footer-brand').forEach(b=>{
  b.querySelectorAll(':scope > img,:scope > svg').forEach(x=>x.remove());
 });
}
function categoryAccent(){
 const map={investment:'#0D9488',loan:'#D97706',banking:'#2563EB',retirement:'#7C3AED',salary:'#DB2777',business:'#0891B2'};
 let key='';
 if(typeof CALCULATORS!=='undefined'){
  const file=(location.pathname.split('/').pop()||'').replace(/\.html$/,'');
  const c=CALCULATORS.find(x=>x.slug===file);
  if(c)key=c.category;
 }
 if(!key){const tag=document.querySelector('.calc-category-tag')?.textContent?.toLowerCase()||'';key=tag.includes('loan')?'loan':tag.includes('bank')?'banking':tag.includes('retire')?'retirement':tag.includes('salary')||tag.includes('income')?'salary':tag.includes('business')?'business':'investment';}
 const color=map[key]||map.investment;
 document.documentElement.style.setProperty('--wa-category-accent',color);
 document.querySelectorAll('.calc-widget,.calc-main .wa-portfolio-card,.calc-main .calc-result').forEach(el=>el.classList.add('wa-category-card'));
}
function css(){if(document.getElementById('wa-final-polish-css'))return;let s=document.createElement('style');s.id='wa-final-polish-css';s.textContent='.footer-mark{display:inline-flex!important;align-items:center;gap:10px;font-weight:850;font-size:20px;line-height:1.1;letter-spacing:-.04em}.wa-footer-logo{width:30px;height:30px;display:block;flex:0 0 30px;object-fit:contain}.footer-mark sup{font-size:8px;align-self:flex-start;margin-top:1px}.wa-category-card{border-color:color-mix(in srgb,var(--wa-category-accent) 48%,var(--line))!important;box-shadow:0 0 0 1px color-mix(in srgb,var(--wa-category-accent) 10%,transparent),var(--shadow)}.wa-category-card .calc-result-row{border-bottom-color:color-mix(in srgb,var(--wa-category-accent) 18%,var(--line))}.wa-category-card .field input:focus,.wa-category-card .field select:focus{border-color:color-mix(in srgb,var(--wa-category-accent) 70%,var(--line));box-shadow:0 0 0 3px color-mix(in srgb,var(--wa-category-accent) 10%,transparent)}.wa-scale-safe{margin-top:14px;border:1px solid var(--line);border-radius:15px;padding:16px;background:var(--surface2)}.wa-scale-safe-head{margin-bottom:12px}.wa-scale-safe-head span{font-size:9px;letter-spacing:.14em;color:var(--accent);font-weight:850}.wa-scale-safe-head h3{margin:3px 0;font-size:15px}.wa-scale-safe-head p{margin:0;color:var(--muted);font-size:10px}.wa-pie-wrap{display:grid;grid-template-columns:150px 1fr;gap:18px;align-items:center}.wa-pie-wrap svg{width:150px;height:150px;display:block}.wa-pie-row{display:grid;grid-template-columns:10px 1fr auto;gap:7px;align-items:center;padding:7px 0;border-top:1px solid var(--line);font-size:10px}.wa-pie-row i{width:9px;height:9px;border-radius:50%;display:block}.wa-pie-row b{font-size:10px}.wa-print-logo{width:46px;height:46px;object-fit:contain;vertical-align:middle;margin-right:10px}.wa-print-brand{display:flex;align-items:center;font-weight:800;font-size:13px;letter-spacing:.08em;margin-bottom:18px}@media(max-width:600px){.wa-pie-wrap{grid-template-columns:1fr}.wa-pie-wrap svg{margin:auto}.footer-mark{font-size:19px}}
';document.head.appendChild(s);}
function rows(){return Array.from(document.querySelectorAll('.calc-result-row')).map(r=>({label:r.querySelector('.calc-result-label')?.textContent?.trim()||'',text:r.querySelector('.calc-result-value')?.textContent?.trim()||'',value:cleanNum(r.querySelector('.calc-result-value')?.textContent||'')})).filter(r=>r.label);}
function pieParts(rs){const find=re=>rs.find(r=>re.test(r.label));let a,b;a=find(/money invested|invested amount|principal|original investment|loan amount|original amount|money deposited/i);b=find(/growth|returns|profit|interest earned|total interest/i);if(a&&b&&a.value>=0&&b.value>=0&&(a.value+b.value)>0)return[a,b];const total=find(/future value|maturity value|total amount|final value|total repayment/i),gain=find(/interest earned|growth|returns|total interest|profit/i);if(total&&gain&&total.value>=gain.value&&gain.value>=0)return[{label:'Original amount',value:total.value-gain.value,text:String(total.value-gain.value)},{label:gain.label,value:gain.value,text:gain.text}];return null;}
function renderSafe(host){if(!host)return;let rs=rows(),parts=pieParts(rs);if(!parts)return;let total=parts.reduce((s,x)=>s+x.value,0);if(!Number.isFinite(total)||total<=0)return;let colors=['#2563eb','#14b8a6','#7c3aed','#f59e0b'],angle=-90,arcs='',legend='';function pt(a,r){let q=a*Math.PI/180;return[50+r*Math.cos(q),50+r*Math.sin(q)]}function path(a,b){let p1=pt(a,42),p2=pt(b,42),large=b-a>180?1:0;return`M 50 50 L ${p1[0].toFixed(2)} ${p1[1].toFixed(2)} A 42 42 0 ${large} 1 ${p2[0].toFixed(2)} ${p2[1].toFixed(2)} Z`}parts.forEach((p,i)=>{let pct=p.value/total*100,end=angle+pct*3.6,mid=(angle+end)/2,q=pt(mid,25);arcs+=`<path d="${path(angle,end)}" fill="${colors[i%colors.length]}"></path>`;if(pct>=8)arcs+=`<text x="${q[0].toFixed(2)}" y="${(q[1]+2).toFixed(2)}" text-anchor="middle" fill="#fff" font-size="7" font-weight="800">${pct<10?pct.toFixed(1):pct.toFixed(0)}%</text>`;legend+=`<div class="wa-pie-row"><i style="background:${colors[i%colors.length]}"></i><span>${esc(p.label)}</span><b>${esc(p.text)} · ${pct<10?pct.toFixed(1):pct.toFixed(0)}%</b></div>`;angle=end});host.innerHTML=`<div class="wa-scale-safe"><div class="wa-scale-safe-head"><span>RESULT BREAKDOWN</span><h3>Scale-safe visual</h3><p>Percentages are calculated from genuine components of the same total, so very large numbers remain readable.</p></div><div class="wa-pie-wrap"><svg viewBox="0 0 100 100" role="img" aria-label="Result breakdown">${arcs}<circle cx="50" cy="50" r="14" fill="var(--surface,#fff)"></circle><text x="50" y="51" text-anchor="middle" font-size="9" font-weight="900" fill="currentColor">100%</text></svg><div>${legend}</div></div></div>`;}
function badGraph(host){let svg=host.querySelector('svg');if(!svg)return true;let txt=svg.outerHTML;return /NaN|Infinity|-Infinity/.test(txt)||svg.getBoundingClientRect().width<20||svg.getBoundingClientRect().height<20;}
function graphWatch(){document.querySelectorAll('[id$="-graph"],.wa-portfolio-card').forEach(host=>{let target=host.matches('[id$="-graph"]')?host:host.querySelector('[id$="-graph"]')||host;if(badGraph(target))renderSafe(target);});}
function pdfReport(){let title=document.querySelector('.calc-title')?.textContent?.trim()||document.title.replace(/\s*\|.*$/,'');let inputs=Array.from(document.querySelectorAll('.field')).map(f=>{let l=f.querySelector('label')?.textContent?.trim()||'',v=f.querySelector('input,select')?.value||'';return l?`<tr><td>${esc(l)}</td><td>${esc(v)}</td></tr>`:''}).filter(Boolean).join('');let rr=rows().map(r=>`<tr><td>${esc(r.label)}</td><td>${esc(r.text)}</td></tr>`).join('');let w=window.open('','_blank');if(!w){alert('Please allow pop-ups for Wealth Arrays to save the PDF.');return;}let logo=new URL('/favicon-v2.svg',location.href).href;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)} — Wealth Arrays</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:32px auto;padding:0 24px;color:#101828}h1{font-size:30px;margin:0 0 8px}h2{font-size:17px;margin:26px 0 8px}p{color:#667085}table{width:100%;border-collapse:collapse;border:1px solid #e4e7ec;margin-bottom:22px}td{padding:10px;border-bottom:1px solid #eaecf0}td:last-child{text-align:right;font-weight:700}.brand{display:flex;align-items:center;font-weight:800;font-size:13px;letter-spacing:.08em;margin-bottom:18px}.brand img{width:46px;height:46px;margin-right:10px}.foot{margin-top:28px;color:#667085;font-size:11px}@media print{.no-print{display:none}}</style></head><body><div class="brand"><img src="${esc(logo)}" alt="Wealth Arrays logo">WEALTH ARRAYS</div><h1>${esc(title)}</h1><p>Generated from the assumptions entered in Wealth Arrays.</p><h2>Your inputs</h2><table>${inputs}</table><h2>Your calculated results</h2><table>${rr}</table><div class="foot">Educational estimate only — not financial, tax, legal or investment advice.</div></body></html>`);w.document.close();w.focus();setTimeout(()=>{try{w.print()}catch(e){}},300);}
function bind(){css();tidyHeader();footerLogo();categoryAccent();graphWatch();if(!document.body.dataset.waPdfBound){document.body.dataset.waPdfBound='1';document.addEventListener('click',e=>{let b=e.target.closest('button,.tool-action');if(!b)return;let t=(b.textContent||'').toLowerCase();if(t.includes('pdf')||t.includes('save as pdf')){e.preventDefault();e.stopImmediatePropagation();pdfReport();}},true);}}
function start(){bind();let obs=new MutationObserver(()=>{tidyHeader();footerLogo();categoryAccent();graphWatch();});obs.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
