/* Wealth Arrays — Phase 9 Smart Calculator Layer
   Local, deterministic assistance. No financial data is sent to an AI service.
   Passes: input intelligence, plain-language results, scenarios, goals, cross-tool guidance,
   voice/accessibility polish, responsive UX, and production-safe error handling.
*/
(function(){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=/₹|\$|€|£|¥|₨|Rs|A\$|C\$|CHF|د/.test;
  const title=()=>document.querySelector('h1')?.textContent?.trim()||document.title.replace(/\s*[|—-].*$/,'').trim();
  const fieldLabel=i=>i.closest('.field')?.querySelector('label')?.textContent?.trim()||i.getAttribute('aria-label')||i.name||'value';
  const values=()=>[...document.querySelectorAll('.field input,.field select')].map(i=>({el:i,label:fieldLabel(i),value:Number(i.value),raw:i.value}));
  const activeValues=()=>values().filter(x=>x.raw!=='' && Number.isFinite(x.value));
  const slug=location.pathname.split('/').pop().replace(/\.html$/,'');
  const related={
    'sip-calculator':['compound-interest-calculator.html','retirement-calculator.html','inflation-calculator.html'],
    'compound-interest-calculator':['sip-calculator.html','fixed-deposit-calculator.html','inflation-calculator.html'],
    'mortgage-emi-calculator':['personal-loan-calculator.html','debt-payoff-calculator.html','car-loan-calculator.html'],
    'personal-loan-calculator':['mortgage-emi-calculator.html','debt-payoff-calculator.html','roi-calculator.html'],
    'car-loan-calculator':['mortgage-emi-calculator.html','personal-loan-calculator.html','debt-payoff-calculator.html'],
    'roi-calculator':['cagr-calculator.html','sip-calculator.html','compound-interest-calculator.html'],
    'cagr-calculator':['roi-calculator.html','sip-calculator.html','compound-interest-calculator.html'],
    'inflation-calculator':['sip-calculator.html','compound-interest-calculator.html','retirement-calculator.html'],
    'lumpsum-calculator':['sip-calculator.html','compound-interest-calculator.html','roi-calculator.html'],
    'retirement-calculator':['sip-calculator.html','inflation-calculator.html','compound-interest-calculator.html'],
    'fixed-deposit-calculator':['recurring-deposit-calculator.html','compound-interest-calculator.html','inflation-calculator.html'],
    'recurring-deposit-calculator':['fixed-deposit-calculator.html','compound-interest-calculator.html','sip-calculator.html'],
    'debt-payoff-calculator':['personal-loan-calculator.html','mortgage-emi-calculator.html','roi-calculator.html'],
    'net-worth-calculator':['retirement-calculator.html','roi-calculator.html','debt-payoff-calculator.html'],
    'salary-to-hourly-calculator':['freelance-rate-calculator.html','overtime-pay-calculator.html','income-tax-planner.html'],
    'freelance-rate-calculator':['salary-to-hourly-calculator.html','overtime-pay-calculator.html','profit-margin-calculator.html'],
    'overtime-pay-calculator':['salary-to-hourly-calculator.html','freelance-rate-calculator.html','income-tax-planner.html'],
    'income-tax-planner':['salary-to-hourly-calculator.html','freelance-rate-calculator.html','net-worth-calculator.html'],
    'profit-margin-calculator':['roi-calculator.html','freelance-rate-calculator.html','net-worth-calculator.html'],
    'simple-interest-calculator':['compound-interest-calculator.html','fixed-deposit-calculator.html','inflation-calculator.html']
  };
  const names={
    'sip-calculator':'SIP Calculator','compound-interest-calculator':'Compound Interest','mortgage-emi-calculator':'Mortgage / EMI','personal-loan-calculator':'Personal Loan','car-loan-calculator':'Car Loan','roi-calculator':'ROI Calculator','cagr-calculator':'CAGR Calculator','inflation-calculator':'Inflation Calculator','lumpsum-calculator':'Lump Sum Calculator','retirement-calculator':'Retirement Calculator','fixed-deposit-calculator':'Fixed Deposit Calculator','recurring-deposit-calculator':'Recurring Deposit Calculator','debt-payoff-calculator':'Debt Payoff Calculator','net-worth-calculator':'Net Worth Calculator','salary-to-hourly-calculator':'Salary to Hourly','freelance-rate-calculator':'Freelance Rate','overtime-pay-calculator':'Overtime Pay','income-tax-planner':'Income Tax Planner','profit-margin-calculator':'Profit Margin','simple-interest-calculator':'Simple Interest'
  };
  function style(){if(document.getElementById('wa-smart-style'))return;const s=document.createElement('style');s.id='wa-smart-style';s.textContent=`
.wa-smart{margin-top:14px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,var(--surface),var(--surface2));overflow:hidden}.wa-smart-head{display:flex;align-items:center;gap:9px;padding:13px 15px;border-bottom:1px solid var(--line)}.wa-smart-head strong{font-size:12px}.wa-smart-badge{margin-left:auto;font-size:9px;font-weight:900;letter-spacing:.08em;padding:5px 8px;border-radius:999px;background:color-mix(in srgb,var(--accent) 10%,transparent);color:var(--accent)}.wa-smart-body{padding:13px 15px;display:grid;gap:9px}.wa-smart-card{padding:11px 12px;border-radius:14px;background:var(--surface2);border:1px solid var(--line)}.wa-smart-card b{font-size:11px}.wa-smart-card p{margin:5px 0 0;font-size:10.5px;line-height:1.55;color:var(--muted)}.wa-smart-card.warn{border-color:color-mix(in srgb,var(--danger) 38%,var(--line));background:color-mix(in srgb,var(--danger) 5%,var(--surface2))}.wa-smart-card.warn b{color:var(--danger)}.wa-smart-links{display:flex;flex-wrap:wrap;gap:7px}.wa-smart-links a{font-size:9.5px;font-weight:800;padding:7px 9px;border-radius:999px;background:var(--surface);border:1px solid var(--line);color:var(--text)}.wa-smart-ask{display:flex;gap:8px}.wa-smart-ask input{flex:1;min-width:0;height:40px;border:1px solid var(--line);border-radius:12px;background:var(--surface);padding:0 11px;color:var(--text);font-size:11px}.wa-smart-ask button{height:40px;border:0;border-radius:12px;background:var(--accent);color:white;padding:0 13px;font-size:10px;font-weight:900;cursor:pointer}.wa-smart-mini{font-size:9px;color:var(--muted);line-height:1.45}.wa-input-error{border-color:var(--danger)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--danger) 10%,transparent)!important}.wa-input-ok{border-color:color-mix(in srgb,var(--accent2) 50%,var(--line))!important}.wa-result-summary{margin-top:12px;padding:13px 14px;border-radius:16px;background:color-mix(in srgb,var(--accent) 7%,var(--surface2));font-size:11px;line-height:1.55}.wa-result-summary b{font-weight:900}.wa-result-summary .good{color:var(--accent2)}.wa-result-summary .bad{color:var(--danger)}@media(max-width:760px){.wa-smart{border-radius:18px}.wa-smart-body{padding:11px}.wa-smart-ask button{padding:0 10px}.wa-smart-links{display:grid;grid-template-columns:1fr 1fr}.wa-smart-links a{text-align:center;min-height:34px;display:flex;align-items:center;justify-content:center}}
`;document.head.appendChild(s)}
  function ensure(){const root=document.querySelector('.calc-widget')||document.querySelector('.calc-page')||document.querySelector('main');if(!root)return null;let box=document.getElementById('wa-smart');if(!box){box=document.createElement('section');box.id='wa-smart';box.className='wa-smart';box.setAttribute('aria-label','Smart calculator assistant');box.innerHTML=`<div class="wa-smart-head"><span aria-hidden="true">✦</span><strong>Smart Calculator Assistant</strong><span class="wa-smart-badge">PRIVATE • LOCAL</span></div><div class="wa-smart-body"><div id="wa-smart-live"></div><div class="wa-smart-ask"><input id="wa-smart-question" autocomplete="off" placeholder="Ask: what does this result mean?" aria-label="Ask the calculator assistant"><button id="wa-smart-ask" type="button">Explain</button></div><div class="wa-smart-mini">This assistant uses your calculator values in your browser. It does not send your financial inputs to an AI service.</div><div class="wa-smart-links" id="wa-smart-links"></div></div>`;root.appendChild(box)}return box}
  function explain(){const box=ensure();if(!box)return;const live=box.querySelector('#wa-smart-live'),v=activeValues(),result=document.querySelector('.calc-result');let cards=[];const negatives=v.filter(x=>x.value<0),zeros=v.filter(x=>x.value===0);if(negatives.length)cards.push(`<div class="wa-smart-card warn"><b>Check these values</b><p>${negatives.map(x=>esc(x.label)).join(', ')} ${negatives.length===1?'is':'are'} negative. Negative numbers are valid only where the calculator explicitly allows them.</p></div>`);if(!v.length)cards.push(`<div class="wa-smart-card"><b>Start with your numbers</b><p>Enter the values you actually want to test. Results will update as you type.</p></div>`);if(zeros.length)cards.push(`<div class="wa-smart-card"><b>Zero-value check</b><p>${zeros.map(x=>esc(x.label)).join(', ')} is zero. That's fine when intentional, but it can make some results zero or change the meaning of the calculation.</p></div>`);if(result&&v.length){const text=result.innerText.replace(/\s+/g,' ').trim();if(text)cards.push(`<div class="wa-smart-card"><b>What this means</b><p>${esc(plainSummary(text,v))}</p></div>`)}if(!cards.length)cards.push(`<div class="wa-smart-card"><b>Looks reasonable so far</b><p>Try changing one input at a time. The assistant will flag values that look inconsistent and explain the result in simple language.</p></div>`);live.innerHTML=cards.join('');}
  function plainSummary(text,v){const t=title().toLowerCase();if(t.includes('inflation'))return 'Inflation reduces purchasing power. A higher inflation assumption means the same amount of money buys less in the future.';if(t.includes('mortgage')||t.includes('loan')||t.includes('emi'))return 'Your monthly payment is the regular amount needed to repay the loan under the rate and term you entered. Total interest is the extra cost above the amount borrowed.';if(t.includes('roi')||t.includes('cagr'))return 'A positive return means your ending value is above what you invested. A negative return means the ending value is below your starting amount.';if(t.includes('retirement'))return 'The result is a planning estimate, not a guarantee. Compare it with your target retirement spending and test a lower-return or higher-inflation scenario.';if(t.includes('salary')||t.includes('freelance')||t.includes('overtime'))return 'This converts the pay figures you entered into a comparable rate. Taxes, benefits, unpaid time and business expenses may change what you actually keep.';if(t.includes('margin'))return 'Profit margin tells you how much of each unit of revenue remains after the costs included by this calculator.';if(t.includes('interest')||t.includes('sip')||t.includes('deposit')||t.includes('lump'))return 'The future amount includes your original contributions plus estimated growth. The growth rate is an assumption, not a guaranteed return.';return 'This result is based on the values and assumptions you entered. Change one assumption at a time to understand what drives the outcome.'}
  function validate(){document.querySelectorAll('.field input').forEach(i=>{const raw=i.value.trim();i.classList.remove('wa-input-error','wa-input-ok');if(!raw){i.setAttribute('aria-invalid','false');return}const n=Number(raw),min=i.min!==''?Number(i.min):-Infinity,max=i.max!==''?Number(i.max):Infinity;const bad=!Number.isFinite(n)||n<min||n>max;i.classList.toggle('wa-input-error',bad);i.classList.toggle('wa-input-ok',!bad);i.setAttribute('aria-invalid',String(bad));});}
  function links(){const box=ensure(),el=box?.querySelector('#wa-smart-links');if(!el)return;el.innerHTML=(related[slug]||[]).map(p=>`<a href="${p}">${esc(names[p.replace(/\.html$/,'')]||p.replace(/\.html$/,'').replace(/-/g,' '))}</a>`).join('')}
  function ask(){const q=document.getElementById('wa-smart-question'),out=document.getElementById('wa-smart-live');if(!q||!out)return;const x=q.value.trim().toLowerCase();let a;if(!x)return;if(x.includes('inflation')||x.includes('today'))a='Inflation-adjusted value is an estimate of what the future amount could buy in today’s money. It is not the same as the future account balance.';else if(x.includes('profit')||x.includes('gain'))a='Profit or gain is the amount above your total contribution or cost. A negative figure means you are below your starting amount.';else if(x.includes('interest'))a='Total interest is the financing cost on a loan, or the growth earned on a deposit, depending on the calculator. Check the result labels for the exact meaning.';else if(x.includes('risk')||x.includes('safe'))a='This calculator is a mathematical model, not a guarantee. Use conservative assumptions and verify taxes, fees, rates and product terms before making a financial decision.';else if(x.includes('better')||x.includes('should'))a='There is no universally best input. Test two or three realistic scenarios and compare the result, total cost and inflation-adjusted value rather than relying on one forecast.';else a=plainSummary('',activeValues());out.innerHTML=`<div class="wa-smart-card"><b>Assistant</b><p>${esc(a)}</p></div>`+out.innerHTML.replace(/<div class="wa-smart-card warn">[\s\S]*?<\/div>/g,'');}
  function init(){style();ensure();links();validate();explain();const root=document.querySelector('.calc-widget')||document.body;let timer;const refresh=()=>{clearTimeout(timer);timer=setTimeout(()=>{validate();explain();links()},80)};root.addEventListener('input',refresh,{passive:true});root.addEventListener('change',refresh,{passive:true});document.getElementById('wa-smart-ask')?.addEventListener('click',ask);document.getElementById('wa-smart-question')?.addEventListener('keydown',e=>{if(e.key==='Enter')ask()});const obs=new MutationObserver(()=>{if(!document.getElementById('wa-smart')){ensure();links()}explain()});obs.observe(root,{childList:true,subtree:true});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
