import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const build=fs.readFileSync('scripts/root-cause-build.mjs','utf8');const bundle=fs.readFileSync('wa-calculator-runtime.js','utf8');const siteBundle=fs.readFileSync('wa-site-runtime.js','utf8');
const calculatorPages=['sip-calculator/index.html','compound-interest-calculator/index.html','mortgage-emi-calculator/index.html','roi-calculator/index.html','simple-interest-calculator/index.html','retirement-calculator/index.html','salary-to-hourly-calculator/index.html','profit-margin-calculator/index.html','fixed-deposit-calculator/index.html','recurring-deposit-calculator/index.html','lumpsum-calculator/index.html','cagr-calculator/index.html','car-loan-calculator/index.html','personal-loan-calculator/index.html','debt-payoff-calculator/index.html','inflation-calculator/index.html','net-worth-calculator/index.html','overtime-pay-calculator/index.html','freelance-rate-calculator/index.html','income-tax-scenario-calculator/index.html'];
const siteSources=['wa-core.js','site-runtime.js','final-polish.js','theme-fix.js','phase3-seo.js','phase4-premium.js','homepage-search.js'];const calcSources=['widget.js','calculator-search.js',...siteSources,'calculator-safety.js','calculator-page-init.js','calculator-enhancements.js'];
if(!build.includes("const siteSources=['wa-core.js"))throw new Error('Root-cause build source contract missing');
for(const file of siteSources){const body=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n').trimEnd();const hash=crypto.createHash('sha256').update(body).digest('hex').slice(0,12);if(!siteBundle.includes(`WA CANONICAL MODULE | site | ${file} | sha256:${hash}`))throw new Error(`Site bundle provenance missing for ${file}`);if(!bundle.includes(`WA CANONICAL MODULE | calculator | ${file} | sha256:${hash}`))throw new Error(`Calculator bundle provenance missing for ${file}`)}
for(const file of calcSources.filter(x=>x==='widget.js'||x==='calculator-search.js'||x==='calculator-safety.js'||x==='calculator-page-init.js'||x==='calculator-enhancements.js')){const body=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n').trimEnd();const hash=crypto.createHash('sha256').update(body).digest('hex').slice(0,12);if(!bundle.includes(`WA CANONICAL MODULE | calculator | ${file} | sha256:${hash}`))throw new Error(`Calculator bundle provenance missing for ${file}`)}
if(bundle.includes('WA CANONICAL MODULE | calculator | calculators.js'))throw new Error('Calculator definitions must not be embedded in shared runtime');if(fs.statSync('wa-calculator-runtime.js').size>750000)throw new Error('Calculator runtime exceeded 750 KB');if(fs.statSync('wa-site-runtime.js').size>750000)throw new Error('Site runtime exceeded 750 KB');
for(const page of calculatorPages){const html=fs.readFileSync(page,'utf8');const scripts=[...html.matchAll(/<script\s+src=["']([^"']+)[^>]*><\/script>/gi)].map(m=>path.basename(m[1].split('?')[0]));if(scripts.filter(x=>x==='wa-calculator-runtime.js').length!==1)throw new Error(`${page}: shared calculator runtime count is not 1`);const id=html.match(/data-wa-calculator="([^"]+)"/i)?.[1];if(!id||!fs.existsSync(`calculator-definitions/${id}.js`))throw new Error(`${page}: missing split definition`);for(const file of [...siteSources,'widget.js','calculator-search.js','calculator-safety.js','calculator-page-init.js','calculator-enhancements.js','calculators.js'])if(scripts.includes(file))throw new Error(`${page}: source module still loaded directly: ${file}`)}
if(fs.existsSync('node_modules'))throw new Error('node_modules must never be present in deploy tree');console.log(`Architecture audit PASS — ${calculatorPages.length}/20 calculators have canonical runtime ownership, dedicated search, split definitions, and source provenance.`);
